name: Build Codebase
on:
  push:
    branches: [ main, develop ]

  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  start:
    name: Initial Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Starting Job
        run: |
          echo "Beginning to Build ${{ github.repository }}"

  run_tests:
    name: Build Codebase
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout "${{ github.repository }}"
        uses: actions/checkout@v4

      - name: Set up Node v18.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run Tests
        run: |
          npm run test -- \
            --no-watch \
            --no-progress \
            --browsers=ChromeHeadless \
            --exclude-pattern="**/app.component.spec.ts,**/folder.page.spec.ts"

      - name: Build Codebase
        run: |
          npm run build

        

  end:
    name: The end
    runs-on: ubuntu-latest
    needs: [start, run_tests]
    steps:
      - name: Ending
        run: |
          echo "${{ github.repository }} has been successfully built"