name: Lint Codebase
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  start:
    name: Initial Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Starting Job
        run: |
          echo "Beginning to Lint ${{ github.repository }}"

  run_lint:
    name: Lint Codebase
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout "${{ github.repository }}"
        uses: actions/checkout@v4

      - name: Set up Node v18.19.1
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Comment out outputs usage
        run: |
          find src -type f -name "*.ts" -exec sed -i 's/import.*outputs.*;//g' {} +
          find src -type f -name "*.ts" -exec sed -i 's/outputs\.auth\.aws_region/"us-east-1"/g' {} +
          find src -type f -name "*.ts" -exec sed -i 's/outputs\.auth\.user_pool_id/"mock-user-pool-id"/g' {} +
          find src -type f -name "*.ts" -exec sed -i 's/Amplify\.configure(outputs);//g' {} +

      - name: Install dependencies
        run: |
          npm install --no-package-lock
        env:
          NX_SKIP_NX_CACHE: true

      - name: Lint Codebase
        run: |
          npm run lint

  end:
    name: The end
    runs-on: ubuntu-latest
    needs: [start, run_lint]
    steps:
      - name: Ending
        id: init
        run: |
          echo "${{ github.repository }} has been successfully linted"